# General (hyper)parameters
params:
  seed: 777
  src: en_XX # See https://huggingface.co/facebook/mbart-large-50
  tgt: de_DE # See https://huggingface.co/facebook/mbart-large-50
  lower_case: True # Tokenizer
  normalization: True # Tokenizer
  checkpoint: facebook/mbart-large-50
  max_len: 100
  train_bs: 8 # train batch-size per device
  dev_bs: 8 # dev batch size per device
  test_bs: 8 # test batch size per device
# Dataset setup
dataset:
  train_path: datasets/EN-DE/train.csv
  dev_path: datasets/EN-DE/dev.csv
  test_path: datasets/EN-DE/test.csv
# MLFlow config
mlflow:
  exp_name: EN-DE-MT
  params: "_1"
